### ISSUE TITLE
StatelessとStatefullが複雑に絡み合ってる件

### ISSUE THREAD

**Issue by isshun226** [tttkouyou/flutter-catchup#2]
https://github.com/tttkouyou/flutter-catchup/blob/3bf973db0c2e3479559edc400ac9ce9c9c57e3fb/lib/main.dart#L10
このWidgetにはAppBarとThemeも含まれていますが@tttkouyou が書いてる内容だとAppBarとThemeはState持っていないと思うので分けましょう。

**Comment by tttkouyou** [comment]
mainをstatefulに、それ以外をstatelessに変更しました。

**Comment by isshun226** [comment]
概ね問題なさそうなのでclose
