### ISSUE TITLE
Buttonの色のカスタマイズ機能(?)

### ISSUE THREAD

**Issue by isshun226** [tttkouyou/flutter-catchup#3]
#1 でも触れていますが、こういう機能こそThemeを活用しましょう。
ThemeDataを別ファイルで定義し、それを参照して色を変更する作りにすれば構造がもう少し綺麗になるはずです。

**Comment by isshun226** [comment]
```dart
List<Color> colorCode = [
    Colors.red[500],
    Colors.blue[500],
    Colors.yellow[500],
    Colors.orange,
    Colors.grey,
    Colors.black,
  ];
  List<String> colorName = [
    '赤',
    '青',
    '黄色',
    '橙色',
    '鼠色',
    '黒',
  ];
```
Map使いましょう。これでも動く分には問題ないですが見通しが悪すぎるしわかりづらい。
``ColorCode``という変数名はどちらかというと``#FFF``のようなカラーコードをイメージさせるのであまり良いネーミングではないですし、ここはMapでkeyとvalueに設定して変数名は``Colors``のようにしましょう。

**Comment by tttkouyou** [comment]
mapを使うことには成功し、現在はmapを使う以外の変更はなく、以前のままの処理で色を選択できるようにしています。
themeについては調べたのですが、アプリ内の基本色を変更するというものしか見つからなかったため、活用方法が分からず、行っていません。

**Comment by isshun226** [comment]
ひとまずこのissueは解決できているようなのでcloseしておきます
