### ISSUE TITLE
細かいけどファイル名について

### ISSUE THREAD

**Issue by isshun226** [tttkouyou/flutter-catchup#6]
Widgetなら``UpperCamelCase``にしてください
ファイル名と中身で微妙に違うとなんか不思議な感覚になる

**Comment by tttkouyou** [comment]
一番早く終わりそうだったので、ほかの問題より早く終わらせました。

**Comment by tttkouyou** [comment]
gitでも正しく表記されるようになりました。原因はファイル名の変更をgit mvを使わずに、普通に行ってしまったからのようです。

**Comment by isshun226** [comment]
原因も特定できていて良いと思います。
コマンドラインからgit管理のファイルを削除・変更する時は``git add``できませんからね。
直っているのでcloseします
